// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Talabat.Users.Data;

#nullable disable

namespace Talabat.Users.Data.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    partial class UsersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Users")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Talabat.Users.Domain.CustomerAggregate.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveCheckoutSession")
                        .HasColumnType("jsonb")
                        .HasColumnName("ActiveCheckoutSession");

                    b.Property<string>("Cart")
                        .HasColumnType("jsonb")
                        .HasColumnName("Cart");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Email");

                    b.HasKey("Id");

                    b.ToTable("Customers", "Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1fb673f4-6974-478b-b4eb-b9882dd13c5f"),
                            Email = "customer@gamil.com"
                        });
                });

            modelBuilder.Entity("Talabat.Users.Domain.CustomerAggregate.CustomerAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Address");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("CustomerId");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerAddresses", "Users");
                });

            modelBuilder.Entity("Talabat.Users.Domain.MerchantAggregate.Merchant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Merchants", "Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1fb673f4-6974-478b-b4eb-b9882dd13c5c"),
                            Email = "merchant1@gamil.com"
                        });
                });

            modelBuilder.Entity("Talabat.Users.Domain.CustomerAggregate.CustomerAddress", b =>
                {
                    b.HasOne("Talabat.Users.Domain.CustomerAggregate.Customer", null)
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Talabat.Users.Domain.CustomerAggregate.Customer", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
