// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Talabat.OrderProcessing.Data;

#nullable disable

namespace Talabat.OrderProcessing.Data.Migrations
{
    [DbContext(typeof(OrderProcessingDbContext))]
    [Migration("20251019102823_Test")]
    partial class Test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Talabat.OrderProcessing.Domain.OrderAggregate.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Talabat.OrderProcessing.Domain.OrderAggregate.Order", b =>
                {
                    b.OwnsOne("Talabat.OrderProcessing.Domain.OrderAggregate.OrderStatus", "OrderStatus", b1 =>
                        {
                            b1.Property<int>("OrderId")
                                .HasColumnType("integer");

                            b1.Property<int>("CurrentStatus")
                                .HasColumnType("integer")
                                .HasColumnName("Status");

                            b1.Property<int>("PaymentMethod")
                                .HasColumnType("integer")
                                .HasColumnName("PaymentMethod");

                            b1.Property<int>("PaymentStatus")
                                .HasColumnType("integer")
                                .HasColumnName("PaymentStatus");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("OrderStatus")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
