<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Talabat.Orders\Talabat.Orders.csproj" />
		<ProjectReference Include="..\Talabat.Orders.Contracts\Talabat.Orders.Contracts.csproj" />
		<ProjectReference Include="..\Talabat.Payments.Contracts\Talabat.Payments.Contracts.csproj" />
		<ProjectReference Include="..\Talabat.Products.Contracts\Talabat.Products.Contracts.csproj" />
		<ProjectReference Include="..\Talabat.ProductsManagement.Contracts\Talabat.ProductsManagement.Contracts.csproj" />
		<ProjectReference Include="..\Talabat.SharedKernal\Talabat.SharedKernal.csproj" />
		<ProjectReference Include="..\Talabat.Users.Contracts\Talabat.Users.Contracts.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Ardalis.GuardClauses" Version="5.0.0" />
		<PackageReference Include="ErrorOr" Version="2.0.1" />
		<PackageReference Include="Ardalis.Result" Version="10.1.0" />
		<PackageReference Include="MediatR" Version="13.0.0" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
	</ItemGroup>


	<ItemGroup>
		<InternalsVisibleTo Include="Talabat.Users.UnitTests" />
		<InternalsVisibleTo Include="Talabat.Users.IntegrationTests" />
	</ItemGroup>

</Project>
