// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Talabat.Vender.Infrastructure.Persistence;

#nullable disable

namespace Talabat.Vender.Data
{
    [DbContext(typeof(ProductsManagementDbContext))]
    [Migration("20250928092429_StoreProductGroupsAndOptionsAsJson")]
    partial class StoreProductGroupsAndOptionsAsJson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ModifierModifierGroup", b =>
                {
                    b.Property<Guid>("ModifierGroupsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModifiersId")
                        .HasColumnType("uuid");

                    b.HasKey("ModifierGroupsId", "ModifiersId");

                    b.HasIndex("ModifiersId");

                    b.ToTable("ModifierModifierGroup");
                });

            modelBuilder.Entity("Talabat.Vender.Domain.ProductAggregate.Entities.Modifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Modifiers");
                });

            modelBuilder.Entity("Talabat.Vender.Domain.ProductAggregate.Entities.ModifierGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Max")
                        .HasColumnType("integer");

                    b.Property<int>("Min")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ModifierGroups");
                });

            modelBuilder.Entity("Talabat.Vender.Domain.ProductAggregate.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ModifierModifierGroup", b =>
                {
                    b.HasOne("Talabat.Vender.Domain.ProductAggregate.Entities.ModifierGroup", null)
                        .WithMany()
                        .HasForeignKey("ModifierGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talabat.Vender.Domain.ProductAggregate.Entities.Modifier", null)
                        .WithMany()
                        .HasForeignKey("ModifiersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Talabat.Vender.Domain.ProductAggregate.Product", b =>
                {
                    b.OwnsOne("Talabat.Vender.Domain.ProductAggregate.Customization", "Customization", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ModifierGroups")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ModifierGroups");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Customization")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
