// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Talabat.Vender.Infrastructure.Persistence;

#nullable disable

namespace Talabat.Vender.Data
{
    [DbContext(typeof(ProductsManagementDbContext))]
    partial class ProductsManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ModifierGroupProduct", b =>
                {
                    b.Property<Guid>("ModifierGroupsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("ModifierGroupsId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ModifierGroupProduct");
                });

            modelBuilder.Entity("Talabat.Vender.Domain.ProductAggregate.Entities.Modifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Modifiers");
                });

            modelBuilder.Entity("Talabat.Vender.Domain.ProductAggregate.Entities.ModifierGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Max")
                        .HasColumnType("integer");

                    b.Property<int>("Min")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ModifierGroups");
                });

            modelBuilder.Entity("Talabat.Vender.Domain.ProductAggregate.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ModifierGroupProduct", b =>
                {
                    b.HasOne("Talabat.Vender.Domain.ProductAggregate.Entities.ModifierGroup", null)
                        .WithMany()
                        .HasForeignKey("ModifierGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talabat.Vender.Domain.ProductAggregate.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Talabat.Vender.Domain.ProductAggregate.Entities.ModifierGroup", b =>
                {
                    b.OwnsOne("Talabat.Vender.Domain.ProductAggregate.Entities.ModifierGroupData", "Data", b1 =>
                        {
                            b1.Property<Guid>("ModifierGroupId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ModifierGroupItems")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("Data");

                            b1.HasKey("ModifierGroupId");

                            b1.ToTable("ModifierGroups");

                            b1.WithOwner()
                                .HasForeignKey("ModifierGroupId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
