// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Talabat.Orders.Data;

#nullable disable

namespace Talabat.Orders.Data.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    partial class OrdersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Orders")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Talabat.Orders.Domain.CheckoutSessionAggregate.CheckoutItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CheckoutSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProductId");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.HasKey("Id");

                    b.HasIndex("CheckoutSessionId")
                        .HasDatabaseName("IX_CheckoutItems_CheckoutSessionId");

                    b.ToTable("CheckoutItems", "Orders");
                });

            modelBuilder.Entity("Talabat.Orders.Domain.CheckoutSessionAggregate.CheckoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AddressId");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CustomerId");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PaymentId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ShopId");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_CheckoutSessions_CustomerId");

                    b.ToTable("CheckoutSessions", "Orders");
                });

            modelBuilder.Entity("Talabat.Orders.Domain.OrderAggregate.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CheckoutSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Items");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_Orders_CustomerId");

                    b.HasIndex("ShopId", "CreatedAt")
                        .HasDatabaseName("IX_Orders_ShopId_CreatedAt");

                    b.ToTable("Orders", "Orders");
                });

            modelBuilder.Entity("Talabat.Orders.Domain.CheckoutSessionAggregate.CheckoutItem", b =>
                {
                    b.HasOne("Talabat.Orders.Domain.CheckoutSessionAggregate.CheckoutSession", null)
                        .WithMany("Items")
                        .HasForeignKey("CheckoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Talabat.Orders.Domain.CheckoutSessionAggregate.CheckoutSession", b =>
                {
                    b.OwnsOne("Talabat.Orders.Domain.CheckoutSessionAggregate.CheckoutSessionLifetime", "Lifetime", b1 =>
                        {
                            b1.Property<Guid>("CheckoutSessionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAt");

                            b1.Property<DateTime>("ExpiresAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("ExpiresAt");

                            b1.Property<int>("StoredStatus")
                                .HasColumnType("int")
                                .HasColumnName("Status");

                            b1.HasKey("CheckoutSessionId");

                            b1.ToTable("CheckoutSessions", "Orders");

                            b1.WithOwner()
                                .HasForeignKey("CheckoutSessionId");
                        });

                    b.Navigation("Lifetime")
                        .IsRequired();
                });

            modelBuilder.Entity("Talabat.Orders.Domain.OrderAggregate.Order", b =>
                {
                    b.OwnsOne("Talabat.Orders.Domain.OrderAggregate.Payment", "Payment", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("PaymentId");

                            b1.Property<int>("Status")
                                .HasColumnType("int")
                                .HasColumnName("PaymentStatus");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders", "Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("Talabat.Orders.Domain.CheckoutSessionAggregate.CheckoutSession", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
